### ISSUE TITLE
Вложенный список вместо собственных заданий

### ISSUE THREAD

**Issue by midevelop** [Elbrus-Bootcamp/grok-js-functions#2]
Сейчас задания статичны прописаны в темах. 
Можно переложить это на GitHub, используя markdown https://guides.github.com/features/mastering-markdown/

1. **Обычные функции**
   1. Объявите функцию с именем foo.
   1. Объявите именнованную функцию foo со входящим параметром x. Обозначьте границы тела функции и границы объявления параметров
1. **Вложенные функции**
   1. Объявите функцию foo. Внутри неё объявите функцию bar. Обозначьте границы тела функции foo. Обозначьте границы тела функции bar.
   1.  Объявите функцию foo. Внутри неё объявите функцию bar. Внутри bar объявите функцию baz. Обозначьте границы тела функции foo. Обозначьте границы тела функции bar. Обозначьте границы тела функции baz.

**Comment by midevelop** [comment]
@ehpc Посмотри рабочий пример https://github.com/Elbrus-Bootcamp/grok-js-functions/tree/list-readme-tasks

**Comment by ehpc** [comment]
@midevelop Я знаю, специально не делал так.
